version: '3.8'
services:
  user-mysql:
    image: mysql:5.6
    ports:
      - 3307:3306
    command: [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
#    volumes:
#      - ../../user-mysql/data:/var/lib/mysql
    networks:
      - shopping-plus-network

  product-mysql:
    image: mysql:5.6
    ports:
      - 3308:3306
    command: [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    #    volumes:
    #      - ../../user-mysql/data:/var/lib/mysql
    networks:
      - shopping-plus-network

  user-service:
    build: ../../src/user-service
    image: icedsoul/shopping-plus-user-service
    restart: always
    depends_on:
      - user-mysql
    ports:
      - 21003:8081
    networks:
      - shopping-plus-network

#  zk-center:
#    image: zookeeper
#    restart: always
#    ports:
#      - 2181:2181
#    networks:
#      - withme-network

  frontend:
    build: ../../src/frontend
    image: icedsoul/shopping-plus-ui-service
    restart: always
    ports:
      - 80:8081
    networks:
      - shopping-plus-network

networks:
  shopping-plus-network:
    driver: bridge