spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://shopping-payment-mysql:3306/pay_record?characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://mysql:3306/shopping?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: payment-service
server:
  port: 19693