server:
    port: 19691
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://shopping-login-mysql:3306/user?characterEncoding=utf8&useSSL=false
#        url: jdbc:mysql://mysql:3306/shopping?characterEncoding=utf8&useSSL=false
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
        name: login-service